### ISSUE TITLE
Working with rtsp stream from IP camera.

### ISSUE THREAD

**Issue by starlord263** [rustequal/recface#1]
Hii, can this algorithm work with IP camera, Thank you

**Comment by rustequal** [comment]
Sure. You can experiment with the script "simple_camera.py". You need to change the function "open_cam_onboard" for example in this way:

```
def open_cam_onboard(width, height, fps):
    return cv2.VideoCapture('rtsp://192.168.1.64/1')
```

If everything works, you can transfer this code to the main script "recface.py". You only need to configure the IP camera to output the stream with the parameters:

```
IMAGE_WIDTH, IMAGE_HEIGHT = 1280, 720
CAMERA_FPS = 30
```
(from "recface_config.py")
