### ISSUE TITLE
Issue with make in jetson nano jetpack 4.6

### ISSUE THREAD

**Issue by Galelio1** [rustequal/recface#2]
Hi, I am getting this error whenever i run make inside mtcnn/:

../common/Makefile.config:159: recipe for target 'chobj/create_engines.o' failed

**Comment by rustequal** [comment]
Hi, The project is optimized to work with NVIDIA JetPack 4.5. If you want to use other versions of "JetPack", then you need to change the project code to work with other versions of the "TensorRT" library
